package PreMarcacao;

import Limitador.Principal;
import com.toedter.calendar.JDateChooser;
import gestaofila2.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PrimeiroPasso extends javax.swing.JFrame {

    public PrimeiroPasso() {
        initComponents();
        nomeComp.setDocument(new Principal(60, Principal.TipoEntrada.NOME));
        bi.setDocument(new Principal(13, Principal.TipoEntrada.BI));
        telemovel.setDocument(new Principal(9, Principal.TipoEntrada.NUMERO));
    }
    
 String objectivos;
 String provincias;
 String postos;
 String horas;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        objectivo = new javax.swing.JComboBox<>();
        jLabel73 = new javax.swing.JLabel();
        provincia = new javax.swing.JComboBox<>();
        telemovel = new javax.swing.JTextField();
        bi = new javax.swing.JTextField();
        nomeComp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        posto = new javax.swing.JComboBox<>();
        jButton25 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jButton23 = new javax.swing.JButton();
        hora = new javax.swing.JComboBox<>();
        codigo = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        showC = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        senha001 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton4.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton4.setText("Volatr");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(153, 204, 255));
        jLabel50.setText("Averbamento");

        jLabel51.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(153, 204, 255));
        jLabel51.setText("Apresentar documento que compro-");

        jLabel52.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(153, 204, 255));
        jLabel52.setText("va o averbamento solicitado, emitido");

        jLabel53.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(153, 204, 255));
        jLabel53.setText("pela entidade competente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        jLabel1.setFont(new java.awt.Font("MicroSquare", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Republica de Mocambique");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBar(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        objectivo.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        objectivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecionar---", "Renovacao de BI", "Emissao de BI" }));
        objectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        objectivo.setPreferredSize(new java.awt.Dimension(86, 27));
        objectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objectivoActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel73.setText("Posto de atendimento");

        provincia.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        provincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecionar---", "Maputo Provincia", "Maputo Cidade" }));
        provincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        provincia.setPreferredSize(new java.awt.Dimension(86, 27));
        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });

        telemovel.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        telemovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        telemovel.setPreferredSize(new java.awt.Dimension(64, 20));
        telemovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telemovelActionPerformed(evt);
            }
        });

        bi.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        bi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bi.setPreferredSize(new java.awt.Dimension(64, 20));
        bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biActionPerformed(evt);
            }
        });

        nomeComp.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        nomeComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nomeComp.setPreferredSize(new java.awt.Dimension(64, 20));
        nomeComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel12.setText("Nome completo");

        jLabel39.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel39.setText("Numero de telemovel");

        jLabel69.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel69.setText("Numero de BI");

        jLabel70.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel70.setText("Objectivo");

        jLabel71.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel71.setText("Provincia");

        posto.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        posto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecionar---", "Posto Machava", "Posto Socimol", "Posto Tsalala" }));
        posto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        posto.setPreferredSize(new java.awt.Dimension(86, 27));
        posto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postoActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(0, 0, 0));
        jButton25.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(102, 255, 102));
        jButton25.setText("CONCLUIR");
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jButton25.setMaximumSize(new java.awt.Dimension(84, 27));
        jButton25.setMinimumSize(new java.awt.Dimension(84, 27));
        jButton25.setPreferredSize(new java.awt.Dimension(84, 30));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jPanel34.setBackground(new java.awt.Color(102, 204, 255));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel26.setText("O codigo comprovativo e gerado");

        jLabel27.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel27.setText("apos a conclusao.");

        jLabel28.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel28.setText("E pode ser usado para vusuali-");

        jLabel29.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel29.setText("zar os dados do comprovativo");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));

        dateChooser.setBackground(new java.awt.Color(255, 255, 255));
        dateChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        dateChooser.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dateChooser.setMinimumSize(new java.awt.Dimension(84, 27));
        dateChooser.setPreferredSize(new java.awt.Dimension(87, 27));

        jButton23.setText("Confirmar");
        jButton23.setMaximumSize(new java.awt.Dimension(84, 25));
        jButton23.setMinimumSize(new java.awt.Dimension(84, 25));
        jButton23.setPreferredSize(new java.awt.Dimension(84, 25));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        hora.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecionar hora---", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30" }));
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        hora.setPreferredSize(new java.awt.Dimension(86, 27));
        hora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                horaMouseMoved(evt);
            }
        });
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hora, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        codigo.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel25.setText("Codigo");

        jLabel24.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel24.setText("Data");

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("Primeira via:");

        jLabel7.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 255));
        jLabel7.setText("Certidao de nascimento");

        jLabel8.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("Certidao de nascimento");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 204, 255));
        jLabel9.setText("Segunda via ou perda:");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 255));
        jLabel10.setText("Renovacao de BI:");

        jLabel11.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 204, 255));
        jLabel11.setText("Bilhete de identidade caducado");

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Requisitos para obtencao de BI:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 204, 255));
        jLabel36.setText("INFORMACOES");

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 204, 255));
        jLabel37.setText("E GUIA DE");

        jLabel38.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 204, 255));
        jLabel38.setText("PRE-MARCACAO");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 204, 255));
        jLabel13.setText("Averbamento");

        jLabel14.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 255));
        jLabel14.setText("va o averbamento solicitado, emitido");

        jLabel15.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 204, 255));
        jLabel15.setText("Apresentar documento que compro-");

        jLabel19.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 204, 255));
        jLabel19.setText("pela entidade competente");

        jLabel46.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(153, 204, 255));
        jLabel46.setText("Dados");

        jLabel47.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 204, 255));
        jLabel47.setText("Preencha os dados correctamente e");

        jLabel48.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(153, 204, 255));
        jLabel48.setText("insira os dados verdadeiros.");

        jLabel49.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("-------------------------------------------------------------------------");

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Preechemento de dados");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        jLabel55.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 204, 255));
        jLabel55.setText("o coprovativo ou usar a senha do");

        jLabel56.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 204, 255));
        jLabel56.setText("Use o codigo gerado para visualizar o");

        jLabel57.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 204, 255));
        jLabel57.setText("usuario");

        jLabel58.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("pre-marcado, para prossecucao dos ");

        jLabel59.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Conserve o comprovativo ate o dia ");

        jLabel60.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("do tratamento de BI");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel60)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel75.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel75.setText("BEM-VINDO A PRE-MARCACAO PARA BI");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        senha001.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        senha001.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        senha001.setPreferredSize(new java.awt.Dimension(64, 20));
        senha001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha001ActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Insira a senha do usuario");

        jButton26.setBackground(new java.awt.Color(0, 0, 0));
        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(102, 255, 102));
        jButton26.setText("Visuailzar comprovativo");
        jButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        jButton26.setMaximumSize(new java.awt.Dimension(84, 25));
        jButton26.setMinimumSize(new java.awt.Dimension(84, 25));
        jButton26.setPreferredSize(new java.awt.Dimension(84, 35));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(0, 0, 0));
        jButton27.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(102, 255, 102));
        jButton27.setText("CONCLUIR");
        jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jButton27.setMaximumSize(new java.awt.Dimension(84, 27));
        jButton27.setMinimumSize(new java.awt.Dimension(84, 27));
        jButton27.setPreferredSize(new java.awt.Dimension(84, 30));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Comprovativo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senha001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel74))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(senha001, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomeComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel70)
                                        .addComponent(jLabel69)
                                        .addComponent(objectivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(telemovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(provincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(posto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(showC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel24))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(nomeComp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(33, 33, 33))
                            .addComponent(objectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MicroSquare", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Gestao de filas");

        jLabel3.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Pre-marcacao para o tratamento de BI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LoginUsuario tela = new LoginUsuario();
        tela.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void objectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objectivoActionPerformed
        // TODO add your handling code here:
        if(objectivo.getSelectedIndex() == 1){
            objectivos = "Renovacao de BI";
        }else if(objectivo.getSelectedIndex() == 2){
            objectivos = "Emissao de BI";
        }
    }//GEN-LAST:event_objectivoActionPerformed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
        if(provincia.getSelectedIndex() == 1){
            provincias = "Maputo Provincia";
        }else if(provincia.getSelectedIndex() == 2){
            provincias = "Maputo Cidade";
        }
    }//GEN-LAST:event_provinciaActionPerformed

    private void telemovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telemovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telemovelActionPerformed

    private void biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biActionPerformed

    private void nomeCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompActionPerformed

    private void postoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postoActionPerformed
        // TODO add your handling code here:
        if(posto.getSelectedIndex() == 1){
            postos = "Posto Machava";
        }else if(posto.getSelectedIndex() == 2){
            postos = "Posto Socimol";
        }else if(posto.getSelectedIndex() == 3){
            postos =  "Posto Tsalala";
        }
    }//GEN-LAST:event_postoActionPerformed
         
    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        //PRE-MARCAR
        try{
            FileReader open0 = new FileReader("Cadastro.txt");
            BufferedReader openning0 = new BufferedReader(open0);
            ArrayList<Usuario> list0 = new ArrayList();
            
            String[] lista0;
            String linha0 = openning0.readLine();
            
            while(linha0 != null){
                 lista0 = linha0.split(";");
                 
                 String nome = lista0[0];
                 String apelido = lista0[1];
                 String dataNascimento = lista0[2];
                 String dataDesconhecida = lista0[3];
                 String bi = lista0[4];
                 String sexos = lista0[5];
                 String celular = lista0[6];
                 String email = lista0[7];
                 String usuario = lista0[8];
                 String senha = lista0[9];
                 String senhaConf = lista0[10];
                 list0.add(new Usuario( nome, apelido,dataNascimento, dataDesconhecida, bi, sexos, 
                                        celular,email, usuario,senha,senhaConf));                
                 linha0 = openning0.readLine();
            }  
            
            FileWriter open = new FileWriter("DadosPreMarcacao.txt", true);
            BufferedWriter openned = new BufferedWriter(open);

            FileReader abrir = new FileReader("DadosPreMarcacao.txt");
            BufferedReader ler = new BufferedReader(abrir);
            ArrayList<DadosPreMarcacao> list = new ArrayList();

            String[] lista;
            String linha = ler.readLine();
            while(linha != null){
                lista = linha.split(";");
                
                String usuario = lista[0];
                String nomeComp = lista[1];
                String telemovel = lista[2];
                String bi = lista[3];
                String objectivos = lista[4];
                String provincias = lista[5];
                String postos = lista[6];
                String tempo = lista[7];
                String horas = lista[8];
                String codigo = lista[9];
                list.add(new DadosPreMarcacao(usuario, nomeComp, telemovel, bi, objectivos, provincias, postos,
                                              tempo, horas, codigo));
               
            linha = ler.readLine();
        }
        //CODIGO DE COMPROVATIVO
        int limite = 26;
        int limit = 26;
        int limitt = 26;
        String[] letras = {"A","B","C","D","E","F","G","H","I","J","K","L","M"
            ,"N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
        String[] letra = {"A","B","C","D","E","F","G","H","I","J","K","L","M"
            ,"N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
        String[] letrass = {"A","B","C","D","E","F","G","H","I","J","K","L","M"
            ,"N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};

        Random rand = new Random();
        String letters = letras[rand.nextInt(limite)];
        String letter = letra[rand.nextInt(limit)];
        String leter = letrass[rand.nextInt(limitt)];
        
        Date data = new Date();

        String hora = data.toString();
        String codigos = hora.substring(8, 10) +  hora.substring(24, 28);
        String codigo01 = letters + letter + leter + codigos;
         //SE O CODIGO FOR IGUAL
        String codigo02 = letters + letter + leter + codigos;
        
        for(int x = 0; x < list0.size(); x++){
              Usuario puxar = list0.get(x);
        for(int z = 0; z < list.size(); z++){
            DadosPreMarcacao get = list.get(z);
             
            if(nomeComp.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "INSIRA O NOME COMPLETO");
            }else if(telemovel.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "INSIRA O NUMERO D TELEMOVEL");
            }else if(bi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "INSIRA O NUMERO DE BI");
            }else if(objectivos.isEmpty() && objectivos == null){
                JOptionPane.showMessageDialog(null, "SELECIONE O OBJECTIVO");
            }else if(provincias.isEmpty() && provincias == null){
                JOptionPane.showMessageDialog(null, "SELECIONE A PROVINCIA");
            }else if(postos.isEmpty() && postos == null){
                JOptionPane.showMessageDialog(null, "SELECIONE O POSTO");
            }else if(horas.isEmpty() && horas == null){
                JOptionPane.showMessageDialog(null, "SELECIONE A HORA");
            }else{
                            
            String datas = data.toString().substring(0,10);
            String dt = data.toString().substring(8, 10);
            String dtas = data.toString().substring(23, 28);
            String date0 = datas.toString() + dtas.toString();
            //datas SAT APR 09 2023
       
            JDateChooser dateChooser1 = dateChooser;
            String tempo =  dateChooser1.getDate().toString().substring(0, 10);
            String dt1 = dateChooser1.getDate().toString().substring(8, 10);
            String tempos = dateChooser1.getDate().toString().substring(23, 28);
            String time = tempo + tempos;
            //tempo SAT APR 09 2023
            
            int dt00 = Integer.parseInt(dt);
            int dt11 = Integer.parseInt(dt1);
                
            if(tempo.isEmpty() && tempo == null){
                JOptionPane.showMessageDialog(null, "SELECIONE A DATA");
            }else{
                
            if(!tempo.contains("Sun") && !tempo.contains("Sat") && !tempo.contains("Sab") && !tempo.contains("Dom")){

                if(datas.substring(4,7).equals(time.substring(4,7))){//VERIFICACAO DO MES CORRENTE
               
                    if(!get.getTempo().substring(8, 10).equals(dt1) && get.getHoras() == horas){//VERIFICACAO DE HORA
                                                                                                // PRIMEIRA CONDICAO
                        if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(!get.getCodigo().equals(codigo01)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);                                       
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }else if(z == list.size() - 1 && !get.getCodigo().equals(codigo02)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }
                    }else if(!get.getTempo().substring(8, 10).equals(dt1) && get.getHoras() != horas){//VERIFICACAO DE HORA
                                                                                                      //SEGUNDA CONDICAO
                             if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(z == list.size() - 1 && !get.getCodigo().equals(codigo01)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }else if(z == list.size() - 1 && !get.getCodigo().equals(codigo02)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }
                             
                    }else if(get.getTempo().substring(8, 10).equals(dt1) && get.getHoras() != horas){//VERIFICAAO DE HORA
                                                                                                    //TERCEIRA CONDICAO
                             if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(z == list.size() - 1 && !get.getCodigo().equals(codigo01)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }else if(z == list.size() - 1 && !get.getCodigo().equals(codigo02)){
                                        JOptionPane.showMessageDialog(null, "CONCLUIDO1");
                                        openned.write(puxar.getUsuario()+";"+nomeComp.getText()+";"+telemovel.getText()+";"+bi.getText()+";"+objectivos
                                                                     +";"+provincias+";"+postos+";"+time+";"+horas+";"+codigo01);
                                        nomeComp.setText("");
                                        telemovel.setText("");
                                        bi.setText("");
                                        
                                        codigo.setText(codigo01);
                                        openned.newLine();
                                        openned.close();
                                        open.close();
                                    break;
                                    }
                    }else if(z == list.size() - 1){
                            JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA ESSA HORA\n"
                                                               +"HORA OCUPADA");
                                    break;
                                    }
                    }else if(z == list.size() - 1){
                        JOptionPane.showMessageDialog(null, "MES INDISPONIVEL! "+"\n"+"ESCOLHA O MES CORRENTE");
                                    break;
                                    }
                }else if(z == list.size() - 1){
                    JOptionPane.showMessageDialog(null, "A PRE-MARCACAO ESTA PREVISTA PARA OS DIAS"+"\n"+
                        "UTEIS DA SEMANA"+"\n"+"IMPOSSIVEL PRE-MARCAR PARA [SABADOS E DOMINGOS]");
                    break;
                }               
            }   }   }
        }   
        }catch(Exception ex){
               Logger.getLogger(PrimeiroPasso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton25ActionPerformed
    
    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        //CONFIRMAR
        try{
            FileReader abrir = new FileReader("DadosPreMarcacao.txt");
            BufferedReader ler = new BufferedReader(abrir);
            ArrayList<DadosPreMarcacao> list = new ArrayList();

            String[] lista;
            String linha = ler.readLine();
            while(linha != null){
                lista = linha.split(";");

                String usuario = lista[0];
                String nomeComp = lista[1];
                String telemovel = lista[2];
                String bi = lista[3];
                String objectivos = lista[4];
                String provincias = lista[5];
                String postos = lista[6];
                String tempo = lista[7];
                String horas = lista[8];
                String codigo = lista[9];
                list.add(new DadosPreMarcacao(usuario, nomeComp, telemovel, bi, objectivos, provincias, postos,
                    tempo, horas, codigo));
            linha = ler.readLine();
        }
                      
        for(int z = 0; z < list.size(); z++){
            DadosPreMarcacao get = list.get(z);

            Date data = new Date();
            JOptionPane.showMessageDialog(null, get.getHoras().substring(0, 2)+get.getHoras().substring(3, 5));
         //    JOptionPane.showMessageDialog(null, horas.substring(0, 2)+horas.substring(3, 5));
            
            String datas = data.toString().substring(0,10);
            String dt = data.toString().substring(8, 10);
            String dtas = data.toString().substring(23, 28);
            String date0 = datas.toString() + dtas.toString();
            //datas SAT APR 09 2023
                       
            JDateChooser dateChooser1 = dateChooser;
            String tempo =  dateChooser1.getDate().toString().substring(0, 10);
            String dt1 = dateChooser.getDate().toString().substring(8, 10);
            String tempos = dateChooser1.getDate().toString().substring(23, 28);
            String time = tempo + tempos;
            //tempo SAT APR 09 2023
            
           int dt00 = Integer.parseInt(dt);
           int dt11 = Integer.parseInt(dt1);
           int gethoras = Integer.parseInt(get.getHoras().substring(0, 2)+get.getHoras().substring(3, 5));
           int horas1 = Integer.parseInt(horas.substring(0, 2)+horas.substring(3, 5));
                     
            if(!tempo.contains("Sun") && !tempo.contains("Sat") && !tempo.contains("Sab") && !tempo.contains("Dom")){

                if(datas.substring(4,7).equals(time.substring(4,7))){//VERIFICACAO DO MES CORRENTE
               
                    if(!get.getTempo().substring(8, 10).equals(dt1) && gethoras == horas1){//VERIFICACAO DE HORA
                                                                                           // PRIMEIRA CONDICAO
                             if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(z == list.size() - 1){
                                        JOptionPane.showMessageDialog(null, "CONFIRMADO1");
                                    break;
                                    }
                    }else if(!get.getTempo().substring(8, 10).equals(dt1) && gethoras != horas1){//VERIFICACAO DE HORA
                                                                                                     //SEGUNDA CONDICAO
                             if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(z == list.size() - 1){
                                        JOptionPane.showMessageDialog(null, "CONFIRMADO2");
                                    break;
                                    }
                    }else if(get.getTempo().substring(8, 10).equals(dt1) && gethoras != horas1){//VERIFICAAO DE HORA
                                                                                                    //TERCEIRA CONDICAO
                             if(datas.substring(4,7).equals(time.substring(4,7)) && dt11 < dt00){
                                    JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA UM DIA PASSADO!"+"\n"
                                                                        +"ESCOLHA OUTRO DIA, DESDE O DIA CORRENTE ADIANTE" );
                                    break;                
                                   }else if(z == list.size() - 1){
                                        JOptionPane.showMessageDialog(null, "CONFIRMADO3");
                                    break;
                                    }
                    }else if(z == list.size() - 1){
                            JOptionPane.showMessageDialog(null, "IMPOSSIVEL PRE-MARCAR PARA ESSA HORA\n"
                                                               +"HORA OCUPADA");
                                    break;
                                    }
                    }else if(z == list.size() - 1){
                        JOptionPane.showMessageDialog(null, "MES INDISPONIVEL! "+"\n"+"ESCOLHA O MES CORRENTE");
                                    break;
                                    }
                }else if(z == list.size() - 1){
                    JOptionPane.showMessageDialog(null, "A PRE-MARCACAO ESTA PREVISTA PARA OS DIAS"+"\n"+
                        "UTEIS DA SEMANA"+"\n"+"IMPOSSIVEL PRE-MARCAR PARA [SABADOS E DOMINGOS]");
                    break;
                }
            }              
        }catch(Exception ex){
               Logger.getLogger(PrimeiroPasso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void horaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horaMouseMoved
        // TODO add your handling code here:
        /*     try{
            FileReader abrir = new FileReader("DadosPreMarcacao.txt");
            BufferedReader ler = new BufferedReader(abrir);
            ArrayList<DadosPreMarcacao> list = new ArrayList();

            String[] lista;
            String linha = ler.readLine();
            while(linha != null){
                lista = linha.split(";");

                String nomeComp = lista[0];
                String telemovel = lista[1];
                String bi = lista[2];
                String objectivos = lista[3];
                String provincias = lista[4];
                String postos = lista[5];
                String tempo = lista[6];
                String horas = lista[7];
                String codigo = lista[8];
                list.add(new DadosPreMarcacao(nomeComp, telemovel, bi, objectivos, provincias, postos,
                    tempo, horas, codigo));
            linha = ler.readLine();
        }

        for(int z = 0; z < list.size(); z++){
            DadosPreMarcacao validar = list.get(z);

            if(validar.getHoras().equals(horas)){
                JOptionPane.showMessageDialog(null, "INDISPONIVEL");
            }else{
                JOptionPane.showMessageDialog(null, "DISPONIVEL");
            }
        }
        }catch(Exception ex){
            Logger.getLogger(PrimeiroPasso.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_horaMouseMoved

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
        if(hora.getSelectedIndex() == 1){
            horas = "08:00";
        }else if(hora.getSelectedIndex() == 2){
            horas = "08:30";
        }else if(hora.getSelectedIndex() == 3){
            horas = "09:00";
        }else if(hora.getSelectedIndex() == 4){
            horas = "09:30";
        }else if(hora.getSelectedIndex() == 5){
            horas = "10:00";
        }else if(hora.getSelectedIndex() == 6){
            horas = "10:30";
        }else if(hora.getSelectedIndex() == 7){
            horas = "11:00";
        }else if(hora.getSelectedIndex() == 8){
            horas = "011:30";
        }else if(hora.getSelectedIndex() == 9){
            horas = "12:00";
        }else if(hora.getSelectedIndex() == 10){
            horas = "12:30";
        }else if(hora.getSelectedIndex() == 11){
            horas = "13:00";
        }else if(hora.getSelectedIndex() == 12){
            horas = "13:30";
        }else if(hora.getSelectedIndex() == 13){
            horas = "14:00";
        }else if(hora.getSelectedIndex() == 14){
            horas = "14:30";
        }else if(hora.getSelectedIndex() == 15){
            horas = "15:00";
        }else if(hora.getSelectedIndex() == 16){
            horas = "15:30";
        }else if(hora.getSelectedIndex() == 17){
            horas = "16:00";
        }else if(hora.getSelectedIndex() == 18){
            horas = "16:30";
        }
    }//GEN-LAST:event_horaActionPerformed

    private void senha001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha001ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha001ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        //PRE-MARCAR
        try{
            FileWriter open = new FileWriter("DadosPreMarcacao.txt", true);
            BufferedWriter openned = new BufferedWriter(open);

            FileReader abrir = new FileReader("DadosPreMarcacao.txt");
            BufferedReader ler = new BufferedReader(abrir);
            ArrayList<DadosPreMarcacao> list = new ArrayList();

            String[] lista;
            String linha = ler.readLine();
            while(linha != null){
                lista = linha.split(";");
                
                String usuario = lista[0];
                String nomeComp = lista[1];
                String telemovel = lista[2];
                String bi = lista[3];
                String objectivos = lista[4];
                String provincias = lista[5];
                String postos = lista[6];
                String tempo = lista[7];
                String horas = lista[8];
                String codigo = lista[9];
                list.add(new DadosPreMarcacao(usuario, nomeComp, telemovel, bi, objectivos, provincias, postos,
                    tempo, horas, codigo));
                
                 linha = ler.readLine();
        }

        for(int z = 0; z < list.size(); z++){
            DadosPreMarcacao pull = list.get(z);

            String code;
            String codigoPuxado = pull.getCodigo();
            code = JOptionPane.showInputDialog(null, "INSIRA O CODIGO");

            if(codigoPuxado.equals(code)){
                JOptionPane.showMessageDialog(null, "USUARIO: "+pull.getUsuario()+"\n"+"NOME: "+pull.getNomeComp()+"\n"+"TELEMOVEL: "+pull.getTelemovel()+"\n"+"BI: "+pull.getBi()+"\n"+
                    "OBJECTIVO: "+pull.getObjectivos()+"\n"+"PROVINCIA: "+pull.getProvincias()+"\n"+
                    "POSTO: "+pull.getPostos()+"\n"+"DATA: "+pull.getTempo()+"\n"+"HORA: "+pull.getHoras()+"\n"+
                    "CODIGO: "+pull.getCodigo());
                break;
            }else{
                JOptionPane.showMessageDialog(null, "CODIGO INCRRECTO");
                break;
            }
        }
        }catch(Exception ex){
            Logger.getLogger(PrimeiroPasso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
          try{
            FileReader abrir = new FileReader("DadosPreMarcacao.txt");
            BufferedReader ler = new BufferedReader(abrir);
            ArrayList<DadosPreMarcacao> list = new ArrayList();
            
              
            String[] lista;
            String linha = ler.readLine();
            
            while(linha != null){
                 lista = linha.split(";");
                 
                String usuario = lista[0];
                String nomeComp = lista[1];
                String telemovel = lista[2];
                String bi = lista[3];
                String objectivos = lista[4];
                String provincias = lista[5];
                String postos = lista[6];
                String tempo = lista[7];
                String horas = lista[8];
                String codigo = lista[9];
                list.add(new DadosPreMarcacao(usuario, nomeComp, telemovel, bi, objectivos, provincias, postos,
                    tempo, horas, codigo));
                               
                 linha = ler.readLine();
            }        
            
               FileReader open = new FileReader("Cadastro.txt");
            BufferedReader openning = new BufferedReader(open);
            ArrayList<Usuario> list1 = new ArrayList();
          
               String[] lista1;
            String linha1 = openning.readLine();
            
            while(linha1 != null){
                 lista1 = linha1.split(";");
                 
                 String nome = lista1[0];
                 String apelido = lista1[1];
                 String dataNascimento = lista1[2];
                 String dataDesconhecida = lista1[3];
                 String bi = lista1[4];
                 String sexos = lista1[5];
                 String celular = lista1[6];
                 String email = lista1[7];
                 String usuario = lista1[8];
                 String senha = lista1[9];
                 String senhaConf = lista1[10];
                 list1.add(new Usuario( nome, apelido,dataNascimento, dataDesconhecida, bi, sexos, 
                         celular,email, usuario,senha,senhaConf));
                 
                 linha1 = openning.readLine();
            }
            
        for(int z = 0; z < list.size(); z++){
            DadosPreMarcacao pull = list.get(z);
            Usuario validar = list1.get(z);

            if(validar.getSenha().equals(senha001.getText())){
                JOptionPane.showMessageDialog(null, "NOME: "+pull.getNomeComp()+"\n"+"TELEMOVEL: "+pull.getTelemovel()+"\n"+"BI: "+pull.getBi()+"\n"+
                    "OBJECTIVO: "+pull.getObjectivos()+"\n"+"PROVINCIA: "+pull.getProvincias()+"\n"+
                    "POSTO: "+pull.getPostos()+"\n"+"DATA: "+pull.getTempo()+"\n"+"HORA: "+pull.getHoras()+"\n"+
                    "CODIGO: "+pull.getCodigo());
                break;
            }else{
                JOptionPane.showMessageDialog(null, "SENHA INCRRECTA");
                break;
            }
        }
        }catch(Exception ex){
            Logger.getLogger(PrimeiroPasso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton27ActionPerformed
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiroPasso().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bi;
    private javax.swing.JLabel codigo;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<String> hora;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeComp;
    private javax.swing.JComboBox<String> objectivo;
    private javax.swing.JComboBox<String> posto;
    private javax.swing.JComboBox<String> provincia;
    private javax.swing.JTextField senha001;
    private javax.swing.JLabel showC;
    private javax.swing.JTextField telemovel;
    // End of variables declaration//GEN-END:variables
}
