package gestaofila2;

import Limitador.Principal;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Registo extends javax.swing.JFrame {

    public Registo() {
        initComponents();
        nome.setDocument(new Principal(60, Principal.TipoEntrada.NOME));
        apelido.setDocument(new Principal(40, Principal.TipoEntrada.NOME));
        dataNascimento.setDocument(new Principal(10, Principal.TipoEntrada.DATA));
       bi.setDocument(new Principal(13, Principal.TipoEntrada.BI));
      celular.setDocument(new Principal(9, Principal.TipoEntrada.NUMERO));
      usuario.setDocument(new Principal(60, Principal.TipoEntrada.USUARIO));
      senha.setDocument(new Principal(100, Principal.TipoEntrada.SENHA));
      senhaConf.setDocument(new Principal(100, Principal.TipoEntrada.SENHA));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apelido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        sexo = new javax.swing.JComboBox<>();
        sexo1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        senhaConf = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton4.setText("Volatr");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jLabel1.setFont(new java.awt.Font("MicroSquare", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel2.setText("Nova conta do usuario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        nome.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nome.setPreferredSize(new java.awt.Dimension(64, 27));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel4.setText("Primeiro nome");

        apelido.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        apelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        apelido.setPreferredSize(new java.awt.Dimension(64, 27));
        apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel5.setText("Apelido");

        dataNascimento.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        dataNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        dataNascimento.setPreferredSize(new java.awt.Dimension(120, 27));
        dataNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataNascimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataNascimentoMouseExited(evt);
            }
        });
        dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoActionPerformed(evt);
            }
        });
        dataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dataNascimentoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel6.setText("D. Nascimento");

        jLabel7.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel7.setText("D. nascimento Desconhecida");

        bi.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        bi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bi.setPreferredSize(new java.awt.Dimension(64, 27));
        bi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                biMouseExited(evt);
            }
        });
        bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biActionPerformed(evt);
            }
        });
        bi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                biKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel8.setText("Numero de BI");

        jLabel9.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel9.setText("Sexo");

        usuario.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        usuario.setPreferredSize(new java.awt.Dimension(64, 27));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel11.setText("Nome de usuario");

        senha.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        senha.setPreferredSize(new java.awt.Dimension(64, 27));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel12.setText("Senha");

        jLabel13.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel13.setText("Senha de conformacao");

        jLabel14.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel14.setText("Numero de celular");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 255, 102));
        jButton5.setText("Concluir");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        sexo.setFont(new java.awt.Font("MicroSquare", 0, 16)); // NOI18N
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "Masculino", "Feminino" }));
        sexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        sexo.setPreferredSize(new java.awt.Dimension(101, 27));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });

        sexo1.setFont(new java.awt.Font("MicroSquare", 0, 16)); // NOI18N
        sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Verdade", "Falso" }));
        sexo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        sexo1.setPreferredSize(new java.awt.Dimension(103, 27));
        sexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 255, 51));
        jButton6.setText("Limpar");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        email.setPreferredSize(new java.awt.Dimension(64, 27));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailMouseReleased(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("MicroSquare", 1, 18)); // NOI18N
        jLabel15.setText("Email");

        celular.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        celular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        celular.setPreferredSize(new java.awt.Dimension(64, 27));
        celular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                celularMouseReleased(evt);
            }
        });
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        senhaConf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        senhaConf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        senhaConf.setMinimumSize(new java.awt.Dimension(64, 27));
        senhaConf.setPreferredSize(new java.awt.Dimension(90, 27));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apelido, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senhaConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(132, 132, 132))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MicroSquare", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginUsuario tela = new LoginUsuario();
        tela.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoActionPerformed

    private void dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dataNascimentoActionPerformed

    private void biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(nome.getText().equals("")){
             JOptionPane.showMessageDialog(null, "E Obrigatoria Preencher o campo nome", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
         if(apelido.getText().equals("")){
             JOptionPane.showMessageDialog(null, "E Obrigatoria  escrever o seu Apelido", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
          if(dataNascimento.getText().equals("")){
             JOptionPane.showMessageDialog(null, "E Obrigatoria  colocar a data de nascimento", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
           if(bi.getText().equals("")){
             JOptionPane.showMessageDialog(null, "E Obrigatoria Insiri a data de Nascimento", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
            if(celular.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Digite o seu numero de Celular", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
            }
         if(senha.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Por favor digite uma senha a sua escolha", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
         if(usuario.getText().equals("")){
             JOptionPane.showMessageDialog(null, "E Obrigatoria Preencher o campo Usuario", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
          if(senhaConf.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Confirma a sua Senha", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
     
        int limite = 400;
        String[] numeros = {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20",
                    "21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40",
                    "41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60",
                    "61","06","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80",
                    "81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100",
                    "101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120",
                    "121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140",
                    "141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160",
                    "161","106","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180",
                    "181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200",
                    "201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220",
                    "221","222","223","224","225","226","227","228","229","230","231","232","233","334","235","236","237","238","239","240",
                    "241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260",
                    "261","206","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280",
                    "281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300",
                    "301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320",
                    "321","322","323","324","325","326","327","328","329","330","331","332","333","334","335","336","337","338","339","340",
                    "341","342","343","344","345","346","347","348","349","350","351","352","353","354","355","356","357","358","359","360",
                    "361","306","363","364","365","366","367","368","369","370","371","372","373","374","375","376","377","378","379","380",
                    "381","382","383","384","385","386","387","388","389","390","391","392","393","394","395","396","397","398","399","400"};
                Random rand = new Random();
                String aleatorio = numeros[rand.nextInt(limite)];
         
        try{
        FileWriter open = new FileWriter("Cadastro.txt", true);
        BufferedWriter openning = new BufferedWriter(open); 
    
        for(int x = 1; x == x; x++){
    if(nome.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "INSIRA O NOME");    
        
        }else if(apelido.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "INSIRA O APELIDO"); 
             break;
                 
            }else if(dataNascimento.getText().isEmpty()){ 
                 JOptionPane.showMessageDialog(null, "INSIRA A DATA DE NASCIMENTO"); 
                 break;
                        
                }else if(bi.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null, "INSIRA O NUMERO DE BI");  
                     break;
                                
                    }else if(celular.getText().isEmpty()){
                         JOptionPane.showMessageDialog(null, "INSIRA O NUMERO DE CELULAR");  
                         break;
                            }else if(email.getText().isEmpty()){
                                JOptionPane.showMessageDialog(null, "INSIRA O EMAIL");
                                break;  
                              
                        }else if(usuario.getText().isEmpty()){
                             JOptionPane.showMessageDialog(null, "INSIRA O USUARIO");  
                             break;
                                
                    }else if(senha.getText().isEmpty()){
                             JOptionPane.showMessageDialog(null, "INSIRA O NOME");  
                             break;
                      
                }else if(senhaConf.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null, "INSIRA A SENHA DE CONFIRMACAO"); 
                     break;
                     
            }else if(nome.getText() == usuario.getText()){
                     JOptionPane.showMessageDialog(null, "O NOME E O USUARIO NAO PODEM SER O  MESMO"+"\n"+
                                                         "SUGESTAO PARA USUARIO: "+usuario.getText()+aleatorio);
                                                         break;   
                     
        }else if(senha.getText().equals(senhaConf.getText())){
            
              if(email.getText().endsWith("@gmail.com")){
                  
                    JOptionPane.showMessageDialog(null, "CONCLUIDO");
            openning.write(nome.getText()+";"+apelido.getText()+";"+dataNascimento.getText()+";"+dataDesconhecid
                        +";"+bi.getText()+";"+sexos+";"+celular.getText()+";"+email.getText()+";"+usuario.getText()+";"+senha.getText()
                        +";"+senhaConf.getText());        
                        openning.newLine();
                        openning.close();
                        open.close();
                        
                    LoginUsuario tela = new LoginUsuario();
                    tela.setVisible(true);
                    this.hide();
                    break;
        }else{
         JOptionPane.showMessageDialog(null, "FORMATO DE EMAIL INCORRECTO");   
        }        
        }else{
               JOptionPane.showMessageDialog(null, "ERRO DE CONFIRMACAO");
               break;
        }   
        }
            }catch(Exception e){
                
                }      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
        if(sexo.getSelectedIndex() == 1){
            sexos = "Masculino";   
        }else if(sexo.getSelectedIndex() == 2){
            sexos = "Feminino";
        }
    }//GEN-LAST:event_sexoActionPerformed

    private void sexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo1ActionPerformed
        // TODO add your handling code here:
        if(sexo1.getSelectedIndex() == 1){
            dataDesconhecid = "Verdade";
        }else if(sexo1.getSelectedIndex() == 2){
            dataDesconhecid = "Falso";
        }
    }//GEN-LAST:event_sexo1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        apelido.setText("");
        bi.setText("");
        dataNascimento.setText("");
        celular.setText("");
        usuario.setText("");
        senha.setText("");
        senhaConf.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
         if(email.getText().endsWith("@gmail.com")){
            
        }else{
         JOptionPane.showMessageDialog(null, "FORMATO DE EMAIL INCORRECTO");   
        }   
    }//GEN-LAST:event_emailActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        // TODO add your handling code here
    }//GEN-LAST:event_emailMouseExited

    private void dataNascimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataNascimentoMouseEntered
        // TODO add your handling code here:
             
    }//GEN-LAST:event_dataNascimentoMouseEntered

    private void dataNascimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataNascimentoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoMouseExited

    private void biMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biMouseExited
        // TODO add your handling code here
        
    }//GEN-LAST:event_biMouseExited

    private void biKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biKeyTyped
        // TODO add your handling code here:        
        String str = bi.getText();
        if(bi.getText().equals(str.substring(12, 13).toString())){           
        }else{
             JOptionPane.showMessageDialog(null, "FORMATO DE BI INCORRECTO");
        }
    }//GEN-LAST:event_biKeyTyped

    private void dataNascimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataNascimentoKeyTyped
        // TODO add your handling code here:
        String str = dataNascimento.getText();
        
        if(dataNascimento.getText().equals(dataNascimento.getText().substring(2, 3)) 
                && dataNascimento.getText().equals(dataNascimento.getText().substring(5, 6))){
            
        }else{
            JOptionPane.showMessageDialog(null, "INSIRA A DATA NO SEGUINTE FORMATO\n"+
                                                "DIA/MES/ANO = 12/12/2012");
        }
    }//GEN-LAST:event_dataNascimentoKeyTyped

    private void emailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailMouseReleased

    private void celularMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_celularMouseReleased
        // TODO add your handling code here:
        if(celular.getText().startsWith("84")){
            
        }else if(celular.getText().startsWith("82")){
            
        }else if(celular.getText().startsWith("85")){
            
        }else if(celular.getText().startsWith("86")){
            
        }else if(celular.getText().startsWith("87")){
        
        }else if(celular.getText().startsWith("83")){
       
        }else{
            JOptionPane.showMessageDialog(null, "NENHUMA OPERADORA FOI IDENTIFICADA\n"+
                                                 "NESTA SEQUENCIA NUMERICA");
        }
    }//GEN-LAST:event_celularMouseReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailKeyTyped
String sexos;
String dataDesconhecid;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelido;
    private javax.swing.JTextField bi;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField senha;
    private javax.swing.JPasswordField senhaConf;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> sexo1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
